-- ATENÇÃO: este script recria as tabelas e apaga os dados existentes.
-- Execute conectado ao seu próprio schema Oracle.

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE INTERVENCAO_OPERACIONAL CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RELATORIO_PRIORIDADE CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TRECHO_RODOVIA CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EQUIPE_MANUTENCAO CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_INTERVENCAO_OPERACIONAL';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RELATORIO_PRIORIDADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TRECHO_RODOVIA';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EQUIPE_MANUTENCAO';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/

CREATE TABLE EQUIPE_MANUTENCAO (
    ID              NUMBER(10)     NOT NULL,
    NOME            VARCHAR2(100)  NOT NULL,
    ESPECIALIDADE   VARCHAR2(100)  NOT NULL,
    ATIVA           CHAR(1)        DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_EQUIPE_MANUTENCAO PRIMARY KEY (ID),
    CONSTRAINT CK_EQUIPE_ATIVA CHECK (ATIVA IN ('S', 'N'))
);

CREATE TABLE TRECHO_RODOVIA (
    ID                  NUMBER(10)    NOT NULL,
    KM                  NUMBER(6)     NOT NULL,
    ALTURA_VEGETACAO    NUMBER(7,2)   NOT NULL,
    CLIMA               VARCHAR2(10)  NOT NULL,
    MONITORADO          CHAR(1)       DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_TRECHO_RODOVIA PRIMARY KEY (ID),
    CONSTRAINT CK_TRECHO_KM CHECK (KM >= 0),
    CONSTRAINT CK_TRECHO_ALTURA CHECK (ALTURA_VEGETACAO >= 0),
    CONSTRAINT CK_TRECHO_CLIMA CHECK (CLIMA IN ('UMIDO', 'SECO', 'NORMAL')),
    CONSTRAINT CK_TRECHO_MONITORADO CHECK (MONITORADO IN ('S', 'N'))
);

CREATE TABLE INTERVENCAO_OPERACIONAL (
    ID              NUMBER(10)     NOT NULL,
    TRECHO_ID       NUMBER(10)     NOT NULL,
    EQUIPE_ID       NUMBER(10)     NOT NULL,
    TIPO            VARCHAR2(80)   NOT NULL,
    DESCRICAO       VARCHAR2(500),
    DATA_AGENDADA   DATE           NOT NULL,
    STATUS          VARCHAR2(20)   NOT NULL,
    CONSTRAINT PK_INTERVENCAO_OP PRIMARY KEY (ID),
    CONSTRAINT FK_INTERVENCAO_TRECHO FOREIGN KEY (TRECHO_ID)
        REFERENCES TRECHO_RODOVIA (ID),
    CONSTRAINT FK_INTERVENCAO_EQUIPE FOREIGN KEY (EQUIPE_ID)
        REFERENCES EQUIPE_MANUTENCAO (ID),
    CONSTRAINT CK_INTERVENCAO_STATUS CHECK
        (STATUS IN ('PLANEJADA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA'))
);

CREATE TABLE RELATORIO_PRIORIDADE (
    ID              NUMBER(10)      NOT NULL,
    DATA_GERACAO    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    QT_URGENTE      NUMBER(10)      DEFAULT 0 NOT NULL,
    QT_CRITICO      NUMBER(10)      DEFAULT 0 NOT NULL,
    QT_ATENCAO      NUMBER(10)      DEFAULT 0 NOT NULL,
    QT_NORMAL       NUMBER(10)      DEFAULT 0 NOT NULL,
    RESUMO          VARCHAR2(2000)  NOT NULL,
    CONSTRAINT PK_RELATORIO_PRIORIDADE PRIMARY KEY (ID),
    CONSTRAINT CK_RELATORIO_QTD CHECK
        (QT_URGENTE >= 0 AND QT_CRITICO >= 0 AND QT_ATENCAO >= 0 AND QT_NORMAL >= 0)
);

CREATE SEQUENCE SEQ_EQUIPE_MANUTENCAO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TRECHO_RODOVIA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INTERVENCAO_OPERACIONAL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RELATORIO_PRIORIDADE START WITH 1 INCREMENT BY 1 NOCACHE;
