-- Dados de teste do sistema MOTIVA.

INSERT INTO EQUIPE_MANUTENCAO (ID, NOME, ESPECIALIDADE, ATIVA)
VALUES (SEQ_EQUIPE_MANUTENCAO.NEXTVAL, 'Equipe Norte', 'Roçada mecanizada', 'S');
INSERT INTO EQUIPE_MANUTENCAO (ID, NOME, ESPECIALIDADE, ATIVA)
VALUES (SEQ_EQUIPE_MANUTENCAO.NEXTVAL, 'Equipe Sul', 'Pulverização', 'S');

INSERT INTO TRECHO_RODOVIA (ID, KM, ALTURA_VEGETACAO, CLIMA, MONITORADO)
VALUES (SEQ_TRECHO_RODOVIA.NEXTVAL, 10, 22.50, 'NORMAL', 'N');
INSERT INTO TRECHO_RODOVIA (ID, KM, ALTURA_VEGETACAO, CLIMA, MONITORADO)
VALUES (SEQ_TRECHO_RODOVIA.NEXTVAL, 25, 38.00, 'SECO', 'S');
INSERT INTO TRECHO_RODOVIA (ID, KM, ALTURA_VEGETACAO, CLIMA, MONITORADO)
VALUES (SEQ_TRECHO_RODOVIA.NEXTVAL, 42, 56.75, 'UMIDO', 'S');

INSERT INTO INTERVENCAO_OPERACIONAL
    (ID, TRECHO_ID, EQUIPE_ID, TIPO, DESCRICAO, DATA_AGENDADA, STATUS)
VALUES (
    SEQ_INTERVENCAO_OPERACIONAL.NEXTVAL,
    (SELECT MIN(ID) FROM TRECHO_RODOVIA WHERE KM = 42),
    (SELECT MIN(ID) FROM EQUIPE_MANUTENCAO WHERE NOME = 'Equipe Norte'),
    'Roçada Mecanizada',
    'Vegetação acima do limite urgente.',
    TRUNC(SYSDATE) + 1,
    'PLANEJADA'
);

INSERT INTO RELATORIO_PRIORIDADE
    (ID, DATA_GERACAO, QT_URGENTE, QT_CRITICO, QT_ATENCAO, QT_NORMAL, RESUMO)
VALUES (
    SEQ_RELATORIO_PRIORIDADE.NEXTVAL,
    SYSTIMESTAMP,
    1, 0, 1, 1,
    'Carga inicial: 3 trechos analisados.'
);

COMMIT;

SELECT * FROM EQUIPE_MANUTENCAO ORDER BY ID;
SELECT * FROM TRECHO_RODOVIA ORDER BY KM;
SELECT * FROM INTERVENCAO_OPERACIONAL ORDER BY ID;
SELECT * FROM RELATORIO_PRIORIDADE ORDER BY DATA_GERACAO DESC;
